package main

type Card struct {
	Object          string            `json:"object"`
	Id              string            `json:"id"`
	OracleId        string            `json:"oracle_id"`
	MultiverseId    []int             `json:"multiverse_ids"`
	MtgoId          int               `json:"mtgo_id"`
	ArenaId         int               `json:"arena_id"`
	TcgPlayerId     int               `json:"tcgplayer_id"`
	Name            string            `json:"name"`
	Lang            string            `json:"lang"`
	ReleasedAt      string            `json:"released_at"` // date
	URI             string            `json:"uri"`
	ScryfallURI     string            `json:"scryfall_uri"`
	Layout          string            `json:"layout"`
	HighresImage    bool              `json:"highres_image"`
	ImageURIs       map[string]string `json:"image_uris"`
	ManaCost        string            `json:"mana_cost"`
	CMC             float64           `json:"cmc"`
	TypeLine        string            `json:"type_line"`
	OracleText      string            `json:"oracle_text"`
	Colors          []string          `json:"colors"`
	ColorIdentity   []string          `json:"color_identity"`
	Legalities      map[string]string `json:"legalities"`
	Games           []string          `json:"games"`
	Reserved        bool              `json:"reserved"`
	Foil            bool              `json:"foil"`
	Nonfoil         bool              `json:"nonfoil"`
	Oversized       bool              `json:"oversized"`
	Promo           bool              `json:"promo"`
	Reprint         bool              `json:"reprint"`
	Variation       bool              `json:"variation"`
	Set             string            `json:"set"`
	SetName         string            `json:"set_name"`
	SetType         string            `json:"set_type"`
	SetURI          string            `json:"set_uri"`
	SetSearchURI    string            `json:"set_search_uri"`
	ScryfallSetURI  string            `json:"scryfall_set_uri"`
	RulingsURI      string            `json:"rulings_uri"`
	PrintsSearchURI string            `json:"prints_search_uri"`
	CollectorNumber string            `json:"collector_number"`
	Digital         bool              `json:"digital"`
	Rarity          string            `json:"rarity"`
	FlavorText      string            `json:"flavor_text"`
	IllustrationId  string            `json:"illustration_id"`
	CardBackId      string            `json:"card_back_id"`
	Artist          string            `json:"artist"`
	BorderColor     string            `json:"border_color"`
	Frame           string            `json:"frame"`
	FullArt         bool              `json:"full_art"`
	Textless        bool              `json:"textless"`
	Booster         bool              `json:"booster"`
	StorySpotlight  bool              `json:"story_spotlight"`
	EDHRecRank      int               `json:"edhrec_rank"`
	Prices          map[string]string `json:"prices"`
	RelatedURIs     map[string]string `json:"related_uris"`
	PurchaseURIs    map[string]string `json:"purchase_uris"`
}
